name: Release

on:
  push:
    branches:
      - main
      - next

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --include=optional

      - name: Verify package quality
        run: |
          npm run lint
          npm test
          npm run build

      - name: Run semantic release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

  # Job to update main branch after release (only for next branch)
  sync-main:
    name: Sync main branch
    runs-on: ubuntu-latest
    needs: release
    if: github.ref == 'refs/heads/next' && success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Merge next into main
        run: |
          git checkout main
          git pull origin main
          git merge origin/next --no-ff -m "chore: merge next into main [skip ci]"
          git push origin main
