name: Simple Release

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: pkg
        run: |
          echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Fail if tag already exists
        run: |
          TAG="v$(jq -r .version package.json)"
          git fetch --tags
          if git tag | grep -q "^$TAG$"; then
            echo "Tag $TAG already exists. Rejecting push."
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci --include=optional

      - name: Build
        run: npm run build

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v$(jq -r .version package.json)
          release_name: Release v$(jq -r .version package.json)
          draft: false
          prerelease: false

      # Option 1: Publish to NPM (if you want to publish every release)
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Option 2: Publish only on manual trigger (uncomment below)
      # - name: Publish to NPM
      #   if: github.event_name == 'workflow_dispatch'
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Option 3: Publish only on draft release approval (requires more logic)
      #   (Let me know if you want this!)
